### ISSUE TITLE
The extension does has some UI and Functionality bugs

### ISSUE THREAD

**Issue by nachat-ayoub** [isaka-james/dhiwise-copy-extension#3]
UI:
The extension does not add the button until i open its popup and trigger the theme button.

Functionality:
The extension does copy only the code visible because the other code is hidden by the website or trimmed programmatically.

**Comment by isaka-james** [comment]
**UI Issue**

Thank you for bringing this up. The extension is designed to add the button only after you open the popup and trigger the theme button. I intended this as a feature to give users control over when the extension becomes active. This way, the extension doesn’t automatically start working unless you explicitly enable it. If there's a strong preference for the button to be available immediately, I could consider adding a permanent activation option in a future update. Alternatively, feel free to submit a pull request if you'd like to implement this change sooner, and we can review it for merging.

**Functionality Issue**

The extension currently copies only the code that’s visible on the browser. This is because sometimes the rest of the code might be hidden or trimmed by the website’s design. You can maximize the page to copy the entire visible code. On my Chrome setup, this allows copying up to 150 lines of code at once, which is quite effective for most Flutter codes. In my experience, standard Flutter codes aren't usually longer than that, but if they are, you can copy them in sections by scrolling and copying the visible code.

Last week, I used this tool to convert my school tracking bus app, and despite the challenges mentioned, I managed to copy the necessary code. So, don't worry—if your app isn't too large, you can continue using this tool for now. However, if it’s necessary, I plan to push an update tomorrow that will fix some issues, including adding a button to download pictures when the tool detects a picture on display.

Also sorry for late reply, I usually don't engage in coding in weekends..
